<DashboardScreen>:

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 20

        canvas.before:
            Color:
                rgba: 0.07, 0.07, 0.09, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: 'CRICKET SCOREBOARD'
            markup: True
            halign: 'center'
            valign: 'middle'
            text_size: self.size
            font_size: '34sp'
            bold: True
            color: 1, 1, 1, 1
            size_hint_y: .25

        BoxLayout:
            orientation: 'vertical'
            spacing: 18
            size_hint_y: .60

            Button:
                text: 'Create Tournament'
                font_size: '20sp'
                background_normal: ''
                background_color: 0.18, 0.55, 0.95, 1
                color: 1,1,1,1
                bold: True
                on_press: root.create_tournament()

                canvas.before:
                    Color:
                        rgba: self.background_color
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [18]

            Button:
                text: 'Create Team'
                font_size: '20sp'
                background_normal: ''
                background_color: 0.15, 0.75, 0.45, 1
                color: 1,1,1,1
                bold: True
                on_press: root.create_team()

                canvas.before:
                    Color:
                        rgba: self.background_color
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [18]

            Button:
                text: 'Start Match'
                font_size: '20sp'
                background_normal: ''
                background_color: 0.95, 0.45, 0.20, 1
                color: 1,1,1,1
                bold: True
                on_press: root.start_match()

                canvas.before:
                    Color:
                        rgba: self.background_color
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [18]

            Button:
                text: 'Match History'
                font_size: '20sp'
                background_normal: ''
                background_color: 0.60, 0.35, 0.85, 1
                color: 1,1,1,1
                bold: True

                canvas.before:
                    Color:
                        rgba: self.background_color
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [18]

        Label:
            text: 'Powered By Python + Kivy'
            font_size: '14sp'
            color: .7,.7,.7,1
            size_hint_y: .08